"""empty message

Revision ID: bded399a1533
Revises: 079ab554b486
Create Date: 2019-05-17 18:06:07.201777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bded399a1533'
down_revision = '079ab554b486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('votes_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('votes_count', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
